from enum import Enum


class PlayerAction(Enum):
    IDLE = 'IDLE'
    MOVE_FORWARD = 'MOVE_FORWARD'
    MOVE_BACKWARD = 'MOVE_BACKWARD'
    WEAK_PUNCH = 'WEAK_PUNCH'
    MEDIUM_PUNCH = 'MEDIUM_PUNCH'
    HIGH_PUNCH = 'HIGH_PUNCH'
    WEAK_KICK = 'WEAK_KICK'
    MEDIUM_KICK = 'MEDIUM_KICK'
    HIGH_KICK = 'HIGH_KICK'
    WEAK_HIT = 'WEAK_HIT'
    WIN = 'WIN'
    DEFEAT = 'DEFEAT'
    BLOCK = 'BLOCK'
